name: Build OpenVPN Static Binary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up musl and build tools
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            musl-tools \
            autoconf \
            libtool \
            pkg-config \
            libssl-dev \
            linux-headers-$(uname -r) \
            tunctl \
            git

      - name: Clone OpenVPN source
        run: |
          git clone https://github.com/OpenVPN/openvpn.git
          cd openvpn
          git checkout v2.6.14

      - name: Build OpenVPN static binary
        run: |
          cd openvpn
          autoreconf -vi
          CC=musl-gcc ./configure --enable-static --disable-shared
          make -j$(nproc)

      - name: Archive OpenVPN binary
        run: |
          cd openvpn
          cp src/openvpn/openvpn /tmp/openvpn-2.6.14-static
          tar czf /tmp/openvpn-2.6.14-static.tar.gz -C /tmp openvpn-2.6.14-static

      - name: Upload OpenVPN binary as artifact
        uses: actions/upload-artifact@v4.6.2
        with:
          name: openvpn-2.6.14-static
          path: /tmp/openvpn-2.6.14-static.tar.gz
